# Data
data_dir: "my-code01/data/mnist/data"
n_class: 10
patch_size: 50
stride: 50

# Model
n_chan_in: 3
pretrained: true
M: 50  # Candidates (Scout)
K: 10  # Selected (DPS)
D: 64

# Transformer
n_token: 1 # Aggregates K patches to 1 embedding
H: 4
D_k: 16
D_v: 16
D_inner: 128
attn_dropout: 0.1
dropout: 0.1

# Training
lr: 0.001
n_epoch: 10
n_epoch_warmup: 1
device: "cuda"
results_dir: "my-code01/results"
