# Data
num_slides: 5
n_patches: 100
n_class: 2
low_res_size: 32
high_res_size: 64

# Model
n_chan_in: 3
pretrained: false
M: 50  # Candidates for Pass 2 (Scouted)
K: 10  # Final Selected for Transformer (DPS)
D: 64

# Transformer
n_token: 1000
H: 4
D_k: 16
D_v: 16
D_inner: 128
attn_dropout: 0.1
dropout: 0.1

# Training
lr: 0.001
n_epoch: 3
n_epoch_warmup: 0
device: "cuda"
